# docker-compose.yml
version: '3'

services:
  mongodb:
    image: mongo:5.0.15
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./databasefiles:/data/db
    restart: always

  expressapp:
    build: ./expressApi
    ports: 
      - "3000:3000"
    volumes:
      - /expressApi
    depends_on:
      - "mongodb"
