version: '3'

services:
  consumerdb:
    image: mongo:5.0.15
    ports:
      - 27017:27017
    volumes:
      - ./databasefiles/consumer:/data/db
    restart: always
    expose:
      - 27017

  publisherdb:
    image: mongo:5.0.15
    ports:
      - 27018:27017
    volumes:
      - ./databasefiles/publisher:/data/db
    restart: always
    expose:
      - 27018

  expressapp:
    build: ./expressApi
    ports:
      - 5000:5000
    environment:
      - MONGO_URL=mongodb://consumerdb:27017
      - DB_NAME=mydb
      - PORT=5000
    volumes:
      - /expressApi
    depends_on:
      - consumerdb

  publisherservice:
    build: ./publisherservice
    restart: always
    ports:
      - 5001:5001
    environment:
      - PORT=5001
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - rabbitmq
      - publisherdb

  db-exporter:
    image: bitnami/mongodb-exporter:latest
    environment:
      MONGODB_URI: consumerdb://mongo:27017
    restart: always
    ports:
      - 9216:9216
    depends_on:
      - consumerdb

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    ports:
      - 9090:9090
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml

  grafana:
    build: ./grafana
    ports:
      - 3000:3000

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmqdata:/var/lib/rabbitmq/mnesia

volumes:
  prometheus-data:

