name: CI tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ArtiomTr/jest-coverage-report-action@v2
        name: Jest coverage report
        with:
          annotations: failed-tests
          test-script: npm run test
          
      - name: ESLint test
        run: npm run lint
